project_id = "xqyiqzqgshjibxdujzvv"

[functions.send-deposit-notification]
verify_jwt = false

[functions.send-withdrawal-notification]
verify_jwt = false

[functions.upload-payment-proof]
verify_jwt = false
